<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="2">
  <testsuite name="Root Suite" timestamp="2022-03-01T07:55:38" tests="0" file="cypress/integration/02-devportal/004-test/00-tryout-api-invocations-from-swagger-console.spec.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Tryout API invocations" timestamp="2022-03-01T07:55:38" tests="1" time="0.0000" failures="2">
    <testcase name="Tryout API invocations Tryout API invocations from swagger console" time="0.0000" classname="Tryout API invocations from swagger console">
      <failure message="Timed out retrying after 30000ms: `cy.wait()` timed out waiting `30000ms` for the 1st request to the route: `lifeCycleStatus`. No request ever occurred.

https://on.cypress.io/wait" type="CypressError"><![CDATA[CypressError: Timed out retrying after 30000ms: `cy.wait()` timed out waiting `30000ms` for the 1st request to the route: `lifeCycleStatus`. No request ever occurred.

https://on.cypress.io/wait
    at cypressErr (https://localhost:9443/__cypress/runner/cypress_runner.js:174921:18)
    at Object.errByPath (https://localhost:9443/__cypress/runner/cypress_runner.js:174990:10)
    at checkForXhr (https://localhost:9443/__cypress/runner/cypress_runner.js:161302:92)
    at https://localhost:9443/__cypress/runner/cypress_runner.js:161325:28
    at tryCatcher (https://localhost:9443/__cypress/runner/cypress_runner.js:13196:23)
    at Function.Promise.attempt.Promise.try (https://localhost:9443/__cypress/runner/cypress_runner.js:10470:29)
    at whenStable (https://localhost:9443/__cypress/runner/cypress_runner.js:167470:63)
    at https://localhost:9443/__cypress/runner/cypress_runner.js:166968:14
    at tryCatcher (https://localhost:9443/__cypress/runner/cypress_runner.js:13196:23)
    at Promise._settlePromiseFromHandler (https://localhost:9443/__cypress/runner/cypress_runner.js:11131:31)
    at Promise._settlePromise (https://localhost:9443/__cypress/runner/cypress_runner.js:11188:18)
    at Promise._settlePromise0 (https://localhost:9443/__cypress/runner/cypress_runner.js:11233:10)
    at Promise._settlePromises (https://localhost:9443/__cypress/runner/cypress_runner.js:11313:18)
    at Promise._fulfill (https://localhost:9443/__cypress/runner/cypress_runner.js:11257:18)
    at https://localhost:9443/__cypress/runner/cypress_runner.js:12871:46
From Your Spec Code:
    at Context.eval (https://localhost:9443/__cypress/tests?p=cypress/support/index.js:442:6)]]></failure>
    </testcase>
    <testcase name="Tryout API invocations &quot;after all&quot; hook for &quot;Tryout API invocations from swagger console&quot;" time="0.0000" classname="&quot;after all&quot; hook for &quot;Tryout API invocations from swagger console&quot;">
      <failure message="`cy.click()` failed because it requires a DOM element.

The subject received was:

  &gt; `undefined`

The previous command that ran was:

  &gt; `cy.get()`

Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Tryout API invocations`" type="CypressError"><![CDATA[CypressError: `cy.click()` failed because it requires a DOM element.

The subject received was:

  > `undefined`

The previous command that ran was:

  > `cy.get()`

Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Tryout API invocations`
    at ensureElement (https://localhost:9443/__cypress/runner/cypress_runner.js:162678:76)
    at validateType (https://localhost:9443/__cypress/runner/cypress_runner.js:162501:16)
    at $Cy.ensureSubjectByType (https://localhost:9443/__cypress/runner/cypress_runner.js:162537:9)
    at pushSubjectAndValidate (https://localhost:9443/__cypress/runner/cypress_runner.js:171827:12)
    at Context.<anonymous> (https://localhost:9443/__cypress/runner/cypress_runner.js:172102:20)
From Your Spec Code:
    at Context.eval (https://localhost:9443/__cypress/tests?p=cypress/integration/02-devportal/004-test/00-tryout-api-invocations-from-swagger-console.spec.js:181:53)]]></failure>
    </testcase>
  </testsuite>
</testsuites>